apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: autmoation-devops-infrastructure
    notifications.argoproj.io/subscribe.on-deployed.slack: autmoation-devops-infrastructure
spec:
  project: default

  source:
    repoURL: https://github.com/sonali-rajput/nginx-deployment.git
    targetRevision: HEAD
    path: nginx
  destination: 
    server: https://kubernetes.default.svc
    namespace: nginx

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - Validate=false
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
